# Generated by Django 4.1.7 on 2023-04-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskmeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='askmeapp.askmeuser')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('CommonContent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='askmeapp.commoncontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askmeapp.askmeuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('common_content', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='askmeapp.commoncontent')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askmeapp.like')),
                ('tag', models.ManyToManyField(to='askmeapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('common_content', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='askmeapp.commoncontent')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askmeapp.like')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askmeapp.question')),
            ],
        ),
    ]
