# Generated by Django 4.1.7 on 2023-04-09 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askmeapp.like')),
                ('tag', models.ManyToManyField(to='askmeapp.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askmeapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askmeapp.user'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askmeapp.like')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askmeapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askmeapp.user')),
            ],
        ),
    ]
