# Generated by Django 4.1.7 on 2023-04-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askmeapp', '0002_alter_question_content_alter_question_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('common_content', 'user')},
        ),
    ]
